return {
  --   NOTE: not working, why?
  --   'monaqa/dial.nvim',
  --   keys = {
  --     {
  --       '<C-a>',
  --       function()
  --         require('dial.map').manipulate('increment', 'normal')
  --       end,
  --     },
  --     {
  --       '<C-x>',
  --       function()
  --         require('dial.map').manipulate('decrement', 'normal')
  --       end,
  --     },
  --     {
  --       'g<C-a>',
  --       function()
  --         require('dial.map').manipulate('increment', 'gnormal')
  --       end,
  --     },
  --     {
  --       'g<C-x>',
  --       function()
  --         require('dial.map').manipulate('decrement', 'gnormal')
  --       end,
  --     },
  --     {
  --       '<C-a>',
  --       function()
  --         require('dial.map').manipulate('increment', 'visual')
  --       end,
  --       mode = { 'x' },
  --     },
  --     {
  --       '<C-x>',
  --       function()
  --         require('dial.map').manipulate('decrement', 'visual')
  --       end,
  --       mode = { 'x' },
  --     },
  --     {
  --       'g<C-a>',
  --       function()
  --         require('dial.map').manipulate('increment', 'gvisual')
  --       end,
  --       mode = { 'x' },
  --     },
  --     {
  --       'g<C-x>',
  --       function()
  --         require('dial.map').manipulate('decrement', 'gvisual')
  --       end,
  --       mode = { 'x' },
  --     },
  --   },
  --   config = function()
  --     local augend = require 'dial.augend'
  --     require('dial.config').augends:register_group {
  --       default = {
  --         augend.integer.alias.decimal,
  --         augend.integer.alias.hex,
  --         augend.date.alias['%Y/%m/%d'],
  --       },
  --       only_in_visual = {
  --         augend.integer.alias.decimal,
  --         augend.integer.alias.hex,
  --         augend.date.alias['%Y/%m/%d'],
  --         augend.constant.alias.alpha,
  --         augend.constant.alias.Alpha,
  --       },
  --     }
  --
  --     require('dial.config').augends:on_filetype {
  --       typescript = {
  --         augend.integer.alias.decimal,
  --         augend.integer.alias.hex,
  --         augend.constant.new { elements = { 'let', 'const' } },
  --       },
  --     }
  --
  --     require('dial.config').augends:register_group {
  --       default = {
  --         -- uppercase hex number (0x1A1A, 0xEEFE, etc.)
  --         augend.constant.new {
  --           elements = { 'and', 'or' },
  --           word = true, -- if false, "sand" is incremented into "sor", "doctor" into "doctand", etc.
  --           cyclic = true, -- "or" is incremented into "and".
  --         },
  --         augend.constant.new {
  --           elements = { '&&', '||' },
  --           word = false,
  --           cyclic = true,
  --         },
  --       },
  --     }
  --   end,
}
