-- vim.api.nvim_create_autocmd('BufWritePost', {
--   group = 'bufcheck',
--   pattern = '*.py',
--   callback = function()
--     vim.cmd '!ruff --fix %'
--     vim.cmd '!black --quiet %'
--   end,
-- })
--
-- vim.api.nvim_create_autocmd('BufWritePost', {
--   group = 'bufcheck',
--   pattern = '*.ts',
--   callback = function() vim.cmd '!biome format --write %' end,
-- })
--
return {
  -- 'stevearc/conform.nvim',
  -- opts = {
  --   lua = { 'stylua' },
  --   -- Conform will run multiple formatters sequentially
  --   python = { 'ruff_fix', 'black' },
  --
  --   -- Use a sub-list to run only the first available formatter
  --   -- javascript = { { 'prettierd', 'prettier' } },
  --   -- typescript = { { 'prettierd', 'prettier' } },
  --   javascript = { 'biome' },
  --   typescript = { 'biome' },
  --
  --   rust = { 'rustfmt' },
  --   json = { 'biome' },
  --   markdown = { 'taplo' },
  -- },
  -- config = function()
  --   require("conform").setup({
  --     format_on_save = {
  --       -- These options will be passed to conform.format()
  --       timeout_ms = 500,
  --       lsp_fallback = true,
  --     },
  --   })
  -- end
}
